### ISSUE TITLE
Formatting Inconsistencies in Character Sheet

### ISSUE THREAD

**Issue by atomdmac** [Moerill/fvtt-markdown-editor#1]
# Environment

Markdown Editor Module: `0.0.4`
Foundry VTT: `0.6.5`
Browser: Firefox `78.0.1` / `Chromium 83.0.4103.97`
OS: Arch Linux, OSX

# Bug Description

Some editor instances incorrectly apply formatting when saving.  So far I have only found the issue in system-specific Applications so it's possible that changes would need to be made at the system-level.  Still, I'm reporting here in the hopes that it's a more general problem that can be addressed in one place.

## Reproduction Steps

* Add a header (header level doesn't seem to matter)
* Add some normal/paragraph text below it
* Save the changes
* The header formatting will stick but the content below it will be formatted as "code" (ex. `like this`)

## Examples of affected editors:

* `Description` field in DnD5e item/weapon sheet
* `Description` field in Savage Worlds character sheet

## Examples of editors that do not seem affected by the bug:

* `Biography` field in  DnD5e character sheet
* Journal entries

**Comment by Moerill** [comment]
Oh damn, didn't see this before putting this into the official module list.

Thanks for the very good issue report!

can reproduce it.. but.. hmpf what is happening here? :/

**Comment by Moerill** [comment]
Observation:
for some reason the text gets indented 7 (?) spaces when saving.

**Comment by Moerill** [comment]
There is some more weird stuff going on there when saving item descriptions..
even when "just" saving 2 lines with regular words, some random spaces get added.

(Only for items in 5e. If i can fix it i'll check savage worlds)

buut.. thats enough for me for tonight, more testing tomorrow or so

**Comment by atomdmac** [comment]
FWIW, it looks like this happens cumulatively.  That is, if you keep doing edit -> save -> edit -> save, the indent increases by 7 spaces each time you save.

**Comment by Moerill** [comment]
I think i found the issue, but solving it will be another thing:

My testing observations are:
* Content gets saved properly (submit value looks fine, rerender value as well)
* Even in the handlebars helper the values get properly processed
* The extra indentation **only** happens when the *handlebars editor helper* is called inside of a *handlebars partial*

One workaround that i don't like: 
Insert the content *after* the rendering process (e.g. in activateListeners).

Alternative solutions? i don't know....

**Comment by atomdmac** [comment]
One more observation: it looks like for the problematic editor instances, the `editor` helper gets called twice: first with an empty string value for `content` and subsequently with the previously saved value.

**Comment by Moerill** [comment]
For me its only called once, strange.

I'll push a quick patch in the next half hour or so to try to adress this problem (and 1 or 2 styling issues i encountered).

please report backc if the issue st ill persists.

**Comment by atomdmac** [comment]
FWIW, I was able to confirm that editors rendered in top-level templates seem to work fine.  I cut/pasted the editor from the SWADE character sheet's `Background` tab into the top-level `character-sheet.html` template and formatting stays consistent between loading/saving.

With regard to multiple calls to the `editor` helper:  I wonder if this is editor-instance specific.  I had only tested with the `Background`/`Description` editor instance in the SWADE system.

**Comment by Moerill** [comment]
Seems like i need to finally take a look at SWADE for this

**Comment by Moerill** [comment]
Ok ye, i do notice its getting called twice there - but only because there are 2 cases of the editor helper getting caleld (one for advances, one for description), thus 2 calls and 2 created instances

**Comment by atomdmac** [comment]
I just added this code above the `registerHelper` call and it seemed to fix the issue.  I literally _just_ tried this though so I'm not sure if there are other side-effects.

`Handlebars.unregisterHelper('editor');`

**Comment by Moerill** [comment]
oh wait what is the issue with unregisterhelper? something bad?

i.. just added that to the hotfix and pushed it :sweat_smile:

**Comment by atomdmac** [comment]
haha weird - I just pulled down and rebuilt and now it works fine :man_shrugging:   Some of my debugging code may have been getting in the way or something.

**Comment by Moerill** [comment]
ok perfect!
Does the original issue still persist for you? or is it solved?

**Comment by atomdmac** [comment]
Looks to be solved!  Did a quick spot check to make sure that the journal inputs still work as expected and it looks like we're in good shape there, too.  Thanks for your help!  I think we can close this one. :+1:

**Comment by Moerill** [comment]
Perfect, thank you very much for your help there!
