### ISSUE TITLE
Entity links in chat do not work.

### ISSUE THREAD

**Issue by Gingerbreadman32** [Moerill/fvtt-markdown-editor#11]
Module Ver. 0.3.2
FVTT Ver. 0.6.5
Using App, but also on Chromium-based browsers

When using markdown editor in conjunction with Combat Utility Belt's enhanced conditions module it refuses to print the link for the journal entry of the condition, I suspect because markdown doesn't like being surrounded by html tags and the chat message being made uses a template.

Picture: 
![image](https://user-images.githubusercontent.com/10749114/88595064-53bb1a80-d030-11ea-8241-9bca75f7130c.png)

Should be easy to create:
1. Have both:
-  Combat Utility Belt 1.1.3
- MEME 0.3.2
2. Make sure at least Output to Chat is checked in the CUBPuter under Enhanced Conditions
3. Put a condition from enhanced conditions on any token and have it output to chat

I think it would be pretty unreasonable to suggest accounting for every module posting to the chat. My personal suggestion would just be to allow the ability to turn off markdown in chat as a setting, but I'll leave it up to your judgement.

Discord Handle: @Mercedes-Benz#4852

Let me know if I missed something, I can post full module list as well but I tried on a fresh world with just those two and got the same results.

**Comment by Moerill** [comment]
thinking about it its more of a *Meme* bug than anything else.

*Note (to myself) for fixing*: 
Do i really still have to modify the enrichHTML method? if yes find a way that does not impact chat rendering.

Also chat markdown as option is a decent idea, which shouldn't be to much work to implement.
