### ISSUE TITLE
Journal drag and drop not working within journals

### ISSUE THREAD

**Issue by gogrady4117** [Moerill/fvtt-markdown-editor#15]
Module version 3.2 
Foundry version 0.6.5 
Browser Chrome
OS Windows 10

When using markdown and opening a journal with embedded links for other journals the embedded links now show text rather than the entity links themselves that can be clicked on and followed to other journals. 0

With Markdown
![image](https://user-images.githubusercontent.com/34630802/89732858-26e70a00-da17-11ea-9b38-8a813186f759.png)

Without Markdown
![image](https://user-images.githubusercontent.com/34630802/89732884-3cf4ca80-da17-11ea-8528-effdb69e9551.png)

**Comment by Moerill** [comment]
i can see at l east 1 other module (OneJournal) enabled, could you try with all modules disabled, please, and recheck whether the issue persists?

Also i'm kinda confused about the title of the issue and the issue described - i do not see any drag and drop description in the issue, only entity links not working. Or did i misunderstand something?

**Comment by Moerill** [comment]
Also even testing with one journal activated i can't replicate it. 
So please check with all modules disabled and afterwards search for the one causing this issue.
And: check console for any errors when opening journals with entity links.

**Comment by Moerill** [comment]
no reply was given in the last 28 days. I'm closing this issue for now, feel free to create a new issue or comment on this one if this error does reappear.
