### ISSUE TITLE
Request for secret text reveal/conceal via one click by GM

### ISSUE THREAD

**Issue by gogrady4117** [Moerill/fvtt-markdown-editor#16]
Allow for secret text paragraph to be revealed/concealed using icon as utilized in forien's quest mod

![image](https://user-images.githubusercontent.com/34630802/89733039-5fd3ae80-da18-11ea-81b4-0b91c4b2843e.png)

**Comment by Moerill** [comment]
Imo this is out of scope of this module and more of a general module or core feature request.
