### ISSUE TITLE
Requesting compatibility with Forien's Quest Log

### ISSUE THREAD

**Issue by highnrgappalachian** [Moerill/fvtt-markdown-editor#18]
MEME breaks certain vital Quest Log functions like saving quest descriptions and closing out Quest Log windows. 
As per Forien _"it probably expects text editors to be exclusively used on entity sheets and Quest Form is not entity sheet"_.

**Comment by elena-v2** [comment]
At some point, MEME and the Quest Log became incompatible once more - things that use the editor like quest descriptions and GM notes no longer save while using it.
