### ISSUE TITLE
[BUG] short bug description

### ISSUE THREAD

**Issue by masterbouh** [Moerill/fvtt-markdown-editor#31]
**Describe the bug**
Since version 0.4, the 'close' button (to close an journal entry for example) no longer works. Nothing happens when I click on it so it is impossible to close once open

**Desktop (please complete the following information):**
 - firefox or chrome on mac os
 - FVTT Version 0.6.6
 - Module version 0.4

**Comment by Moerill** [comment]
Please do provide some information about errors in console, .. 
Also please do add a proper title in the future.

**Comment by Moerill** [comment]
Please check if your issue persists with 0.4.1
If yes, please create a new issue with some more useful information.

**Comment by masterbouh** [comment]
Sorry, I completely forgot about the title
I did not know how to open the console
0.41 seems to have corrected the bug
Many thanks
